<?php

$title = 'My books';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title) ?></h1>

<table class="table">
    <tr>
        <th>Title</th>
        <th>ISBN</th>
    </tr>
    <?php foreach ($books as $book): ?>
        <tr>
            <td><?php echo $this->escapeHtml($book->title) ?></td>
            <td><?php echo $this->escapeHtml($book->isbn) ?></td>
        </tr>
    <?php endforeach ?>
</table>
