<div class="hero hero-book">
    <div class="row">
        <div class="teaser rounded">
            <h1 class="h1">Your books in the cloud</h1>
            <h2 class="h2">Always loosing focus on your book collection? Now get them back
            organized with <span class="zf-green">Cloud</span>Books</h2>
            <br>
            <p>
                <a href="/more" class="btn btn-default">Learn more</a>
                <a href="<?php echo $this->url('zfcuser/register') ?>" class="btn btn-success">Sign up</a>
            </p>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <h3 class="h3 zf-green"><span class="glyphicon glyphicon-book"></span>&nbsp;Get organized</h3>
        <p>Organize all of your books in a single place with an easy to use interface that works on you desktop, tablet and mobile.</p>
    </div>

    <div class="col-md-4">
        <h3 class="h3 zf-green"><span class="glyphicon glyphicon-search"></span>&nbsp;Brighter insigts</h3>
        <p>Visualize which books you have lend to friends or co-workers and have a public whish-list available so others can gift you a book you like.</p>
    </div>

    <div class="col-md-4">
        <h3 class="h3 zf-green"><span class="glyphicon glyphicon-cloud"></span>&nbsp;Always available</h3>
        <p>Managing your books in the cloud means you can free up the diskspace and have all your books available whenever and wherever you want.</p>
    </div>

</div>