<?php
    $this->headLink()
        ->appendStylesheet($this->basePath('css/pricing.css'));
    $this->headTitle($this->translate('Features'))
?>
<div class="row">

    <h3 class="text-center">Pricing plans</h3>
    <hr>
    <div class="col-sm-4">
        <div class="panel panel-default text-center">
            <div class="panel-heading">
                <h3>Free</h3>
            </div>
            <div class="panel-body">
                <h3 class="panel-title price">$0<span class="price-cents">.00</span><span class="price-month">/mo.</span></h3>
            </div>
            <ul class="list-group">
                <li class="list-group-item">50 Books</li>
                <li class="list-group-item">5 GB of Storage</li>
                <li class="list-group-item">Automated backup</li>
                <li class="list-group-item">Email Support</li>
                <li class="list-group-item">Security Suite</li>
                <li class="list-group-item"><a class="btn btn-default">Sign Up Now!</a></li>
            </ul>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="panel panel-success text-center">
            <div class="panel-heading">
                <h3>Basic</h3>
            </div>
            <div class="panel-body">
                <h3 class="panel-title price">$5<span class="price-cents">.00</span><span class="price-month">/mo.</span></h3>
            </div>
            <ul class="list-group">
                <li class="list-group-item">500 Books</li>
                <li class="list-group-item">50 GB of Storage</li>
                <li class="list-group-item">Automated backup</li>
                <li class="list-group-item">Email Support</li>
                <li class="list-group-item">Security Suite</li>
                <li class="list-group-item"><a class="btn btn-success">Sign Up Now!</a></li>
            </ul>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="panel panel-default text-center">
            <div class="panel-heading">
                <h3>Unlimited</h3>
            </div>
            <div class="panel-body">
                <h3 class="panel-title price">$50<span class="price-cents">.00</span><span class="price-month">/mo.</span></h3>
            </div>
            <ul class="list-group">
                <li class="list-group-item">Unlimited Books</li>
                <li class="list-group-item">5 TB of Storage</li>
                <li class="list-group-item">Automated backup</li>
                <li class="list-group-item">Email Support</li>
                <li class="list-group-item">Security Suite</li>
                <li class="list-group-item"><a class="btn btn-default ">Sign Up Now!</a></li>
            </ul>
        </div>
    </div>
    </div>

</div>